config/routes.rb
Rails.application.routes.draw do
   default_url_options :host => "maropost.dev"
   devise_for :users, controllers: { registrations: "registrations" }
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)
   
   
   root to: 'home#index'

   get 'home/about_us'

   
   resources :contacts, only: [:new, :create]

   resources :photos do
     collection do
       post :import
       get  :counter
     end 
   end
   # post 'auth_user' => 'authentication#authenticate_user'
   namespace :api, defaults: { format: :json } do
     namespace :v1 do
       resources :users, :only => [:show, :create, :update, :destroy]
       resources :photos
     end
   end

   require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    match '/contacts', to: 'contacts#new', via: 'get'

end

app/models/photo.rb
class Photo < ApplicationRecord
  require 'csv'
  require 'open-uri'
  # validate :avatar_size_validation
   mount_uploader :file, PictureUploader
   validates :title, presence: true,uniqueness: true
   validates :file, presence: true
   # paginates_per  6

  def self.import(file)
   CSV.foreach(file.path, headers: true) do |row|
    @imag = row['file']
     p = Photo.new
       p.remote_file_url = @imag
       p.title = row['title']
       p.save!
   end 
 end

  private

  def avatar_size_validation
    errors[:avatar] << "should be less than 5MB" if photo.size > 5.megabytes
  end
end

app/controllers/api/v1/photos_controller.rb
class Api::V1::PhotosController < ApplicationController
   respond_to :json
   skip_before_action :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
   before_action :authenticate_request!


   def index
    photos = Photo.all
	      render :json => { :status => 'success', :photo => photos.as_json() ,:message => 'record fetched successfully' ,:code => '200'}
   end

		  def create
		   photo = Photo.new(photo_params) 
			   if photo.save 
			     render :json => { :status => 'success', :photo => photo.as_json() ,:message => 'photo saved successfully' ,:code => '200'}
			   else
			     render json: { errors: photo.errors}, status: 422 , message: 'failed'
			   end
		  end

		  def show
		  	 photo = Photo.find(params[:id])
			    render :json => { :status => 'success', :photo => photo.as_json() ,:message => 'photo fetched successfully' ,:code => '200'}
		  end

		  def update
		    photo = Photo.find(params[:id])
			    if photo.update(photo_params)
			      render :json => { :status => 'success', :photo => photo.as_json() ,:message => 'photo updated successfully' ,:code => '200'}
			    else
			      render json: { errors: photo.errors }, status: 500
			    end
		  end

		  def destroy
		    photo = Photo.find(params[:id])
		     if photo.destroy
		        render :json => { :status => 'success',:message => 'photo deleted successfully' ,:code => '201'}
		      else
			      render json: { errors: photo.errors }, status: 500
			    end   
		  end

		  private

		  def photo_params
		   params.require(:photo).permit(:title, :file)
		  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photos, only: [:show, :edit, :update, :destroy]
  before_action :get_collection, only: [:index, :update]
  before_action :authenticate_user!


  def import
    begin
      Product.import(params[:file])
      redirect_to photos_path, notice: "Products imported."
    rescue
      redirect_to photos_path, notice: "Invalid CSV file format/No file choosen"
    end
  end

  
  def show
  end


  def counter
   @count = Photo.count
    respond_to do |format|
      format.json { render json: @count}
    end
  end

  
  def new
    @photo = Photo.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  
  def edit
  end

 
  def create
    @photo = Photo.new(photo_params)
      if @photo.save
        redirect_to photos_path, notice: 'Photo was successfully created.'
      else
        render :new ,notice:  'Sorry we cannot add this product.'
      end
  end

  
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_path, notice: 'Photo was successfully updated.' }
        format.js 
      else
        format.js {  }
      end
    end
  end

  
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html {
        flash[:success] = 'Photo was successfully destroyed.'
        redirect_to photos_path
      }
      format.json { head :no_content }
    end
  end

  def get_collection
    @photos = Photo.page(params[:page]).per(6)
  end

  private
    
    def set_photos
      @photo = Photo.find(params[:id])
    end

    
    def photo_params
      params.require(:photo).permit(:title, :file)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{photo.title}" %></h3>
</div>
<div class="modal-header" id="photo-new">
	<%= render 'form', photo: photo %>
</div>

app/views/photos/_form.html.erb
<div class="modal-header" id="photo-modal">
    <%= form_for @photo, remote: true, :html => {:multipart => true} do |form| %>
      <%= render "shared/error_messages", :target => @photo %>
        <div id="error_explanation">
          <div class="err"></div>
        </div>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: 'Enter name' , id: :photo_title ,:required => true,class:'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :file %>
        <%= form.file_field :file, id: :photo_file ,class:'form-control' %>
      </div>

      <div class="actions">
       <%= form.submit class:'btn btn-default' %>
      </div>

  <% end %>
  </div>


<script>
  $('.modal-header').one('submit', function() {
    $(this).find('input[type="submit"]').attr('disabled','disabled');
  });

</script>

app/views/photos/_index.html.erb
<div class="row">
  <% photos.in_groups_of(3) do |group| %>
    <% group.compact.each do |photo| %>
      <% cache(photo, :expires_in => 5.minutes) do %>
       <div class="col-lg-3 col-md-4 col-xs-6 thumb">
         <%= image_tag (photo.file_url), class: "img-sz" %>
           <h4><%= link_to photo.title, photo %></h4>
             <%= link_to "Edit", edit_photo_path(photo) , remote: true, class: "btn btn-default btn-xs" %>
              <%= link_to "delete", photo,remote: true, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-xs" %></br></br>
       </div>
      <% end %>
    <% end %>
  <% end %> 
</div>

app/views/photos/destroy.js.erb
$('#photo-modal').html("<%= j (render @photos) %>")

app/views/photos/edit.html.erb
<%= render 'edit', photo: @photo %>

app/views/photos/edit.js.erb
$(".modal-dialog").html("<%= escape_javascript render(:partial => 'edit', :locals => { photo: @photo }) %>");
$("#myModal").modal("show")

app/views/photos/index.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="count-text">Total Photo Count</div>
  </div>
  <div class="col-md-5 col-md-offset-2"></div>
  <div id="photo_counter"><span class="count"></span></div>
  
</div>

<h1>Photo Gallery</h1>

<div class="ajax-progress"></div>

<h2><%= link_to "Add photo", new_photo_path, class: "btn btn-default"%></h2>

<h3>Import Photos</h3>
  <%= form_tag  import_photos_path, multipart: true do %>
  <%= file_field_tag :file %></br>
  <%= submit_tag "Import Photos" %>
<% end %></br>

<div id="photo_index">
  <%= render 'index', photos: @photos %>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

  </div> 
</div>
<%= paginate @photos %>

<script>
  $(document).ready(function() {
    $(".count-text").css("color", "orange");
      $.ajax({
            type: "GET",// GET in place of POST
            url: "/photos/counter",
            success: function (result) {
               //do somthing here
               $(".count").html(result);
               $(".count-text").css("color", "green");
            },
            error: function (response){
              window.alert("something wrong!");
            }
       });
                                                                                                                                                                                                                                                                                                                                                                         
   });
</script>

<!-- <script>
   $('.count').each(function () {
    $(this).prop('Counter',0).animate({
        Counter: $(this).text()
    }, {
        duration: 4000,
        easing: 'swing',
        step: function (now) {
            $(this).text(Math.ceil(now));
            console.log($(this).html());
            if ($(this).html() < <%#= Photo.count %>) {
             $(".count-text").css("color", "orange");
            } else {
             $(".count-text").css("color", "green");
            } 
        }
    });
});
</script>
 -->

app/views/photos/new.html.erb
<div class="modal-header">
<h3>New Photo</h3>
</div>
<%= render "form" %>


<%= link_to 'Back', photos_path %>

app/views/photos/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'form') %>")
$("#product-modal").modal("show")

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-9">
    <%= image_tag(@photo.file_url, :width => "100%") if @photo.file.present? %>
  </div>

  <div class="col-xs-3">
    <p><b>Title: </b><%= @photo.title%></p>
  </div>
</div>

app/views/photos/update.js.erb
<% if @photo.errors.present? %>
	<% @photo.errors.messages.each do |k,v|%>
	$(".err").html("<%= k %> <%=v[0]%>");
	<% end %>
<% else %>
	$("#photo_index").html("<%= escape_javascript render(:partial => 'index', :locals => { photos: @photos }) %>");

	$("#myModal").modal('hide');
	$('.modal-backdrop').remove();
<% end %>