config/routes.rb
Rails.application.routes.draw do
   default_url_options :host => "maropost.dev"
   devise_for :users, controllers: { registrations: "registrations" }
   devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)
   
   
   root to: 'home#index'

   get 'home/about_us'

   
   resources :contacts, only: [:new, :create]

   resources :photos do
     collection do
       post :import
       get  :counter
     end 
   end
   # post 'auth_user' => 'authentication#authenticate_user'
   namespace :api, defaults: { format: :json } do
     namespace :v1 do
       resources :users, :only => [:show, :create, :update, :destroy]
       resources :photos
     end
   end

   require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    match '/contacts', to: 'contacts#new', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="navbar-default navbar-fixed-bottom">
  <div class="container-fluid">
    <span>Maropost!</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Maropost - Start </title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>
              <li><a href="#"><%= current_user.email %></a></li>
              <li><%= link_to "Home",root_path ,class: cp('/') %></li>
              <li><%= link_to "Contact Us",contacts_path ,class: cp('/contacts') %></li>
              <li><%= link_to "About Us", home_about_us_path,class: cp('/home/about_us') %></li>
              <li><%= link_to "Gallery", photos_path,class: cp('/photos') %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link red_bttn'  %></li>
           <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link blue_bttn'%></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link home_bttn'%></li>
           <% end %>
          </ul>
        </nav>
      </div>
    </header>
  </head>
 <body>
   <div class="container">
    <%= render 'layouts/messages' %> 
      <%= yield %> 
    <%= render 'layouts/footer' %>
   </div>
 </body>
</html>